### ISSUE TITLE
remove external library dependency on curl, openssl, libwebsockets

### ISSUE THREAD

**Issue by kanjoe24** [rdkcentral/ut-control#28]
remove curl & openssl, only ut-control is required here.

_Originally posted by @Ulrond in https://github.com/rdkcentral/ut-core/pull/86#discussion_r1682897008_
            
For this change to happen, need to make ut-control link all external libraries with their static counterparts rather than shared libraries as is being currently done.

**Comment by Ulrond** [comment]
Closed on https://github.com/rdkcentral/ut-control/pull/29
